version: '3'

services:
  remotely-funds-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remotely-funds-backend
    ports:
      - "7777:7777" # Map host port 8080 to container port 80
    volumes:
      - .:/app # Mount the current directory into the container
    networks:
      - php-network
    environment:
        XDEBUG_CONFIG: remote_host=host.docker.internal client_port=9007
        COMPOSER_ALLOW_SUPERUSER: 1
  remotely-funds-redis-server:
    image: redis
  remotely-funds-postgres:
    image: postgres
    container_name: remotely-funds-postgres
    networks:
      - php-network
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
    

networks:
  php-network:
