version: '3'

services:
  cms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms
    ports:
      - "7777:7777" # Map host port 8080 to container port 80
    volumes:
      - .:/app # Mount the current directory into the container
    networks:
      - php-network
    environment:
        XDEBUG_CONFIG: remote_host=host.docker.internal client_port=9007
        COMPOSER_ALLOW_SUPERUSER: 1 
  redis-server:
    image: redis
    ports: 
      - "6379:6379"

networks:
  php-network:
